### ISSUE TITLE
practica1

### ISSUE THREAD

**Issue by grupohernandezalba** [enriquezsofia/Georeferenciados#1]
Bien @enriquezsofia ya casi, solo me marca un error el mapa creo que es el API KEY, checalo

![Captura de Pantalla 2020-02-19 a la(s) 21 21 06](https://user-images.githubusercontent.com/14998558/74897837-da6f1b80-535d-11ea-87d9-d4b5b7ba97e2.png)

**Comment by enriquezsofia** [comment]
Buenas noches profesor @grupohernandezalba, ya chequé la API KEY y era un pequeño error con la URL que le había puesto. Ya carga correctamente.[cid:image003.png@01D5E77E.C92FDB70]

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by grupohernandezalba** [comment]
Muy bien @enriquezsofia . Quizás solo tu index ponerlo en la carpeta de Georeferenciados

**Comment by enriquezsofia** [comment]
Listo, se encuentra en la carpeta de Georeferenciados.
