### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by grupohernandezalba** [enriquezsofia/Georeferenciados#3]
Muy bien. @enriquezsofia me gusto el diseño y que tu menú tiene un efecto de scroll, trata de implementar la opción de editar.

![Captura de Pantalla 2020-03-12 a la(s) 21 42 30](https://user-images.githubusercontent.com/14998558/76587746-88c43780-64aa-11ea-9b3a-0956e38a141b.png)

**Comment by enriquezsofia** [comment]
Listo, ya está implementado
